version: '3.9'

services:
  server:
    image: diplom_server
    ports:
      - '3000:3000'
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'postgres'
      DATABASE: 'postgres2'
      POSTGRES_PORT: 5432
      PORT: 3000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'postgres'
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  data:


